name: Docker Build & Push

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}       # <- must exist in Settings ▸ Secrets ▸ Actions
          password: ${{ secrets.newtoken2 }}      # <- must exist and be marked as secret

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .                              # <- add this if Dockerfile is in repo root
          tags: rupsaojha247/dimage1:latest, rupsaojha247/dimage1:${{ github.run_number }}
